# Generated by Django 3.0.8 on 2020-07-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='Token',
            new_name='token',
        ),
    ]
