# Generated by Django 3.0.8 on 2020-07-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navid', '0002_auto_20200710_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='destination_channels',
            field=models.ManyToManyField(related_name='destination_bots', related_query_name='destination_bot', to='navid.Channel'),
        ),
        migrations.AddField(
            model_name='bot',
            name='source_channels',
            field=models.ManyToManyField(related_name='source_bots', related_query_name='source_bot', to='navid.Channel'),
        ),
    ]
